# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_invite_activation_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='accepted',
        ),
    ]
