# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_invite_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='The company allows a partner organization            to manage support tickets on their behalf.', max_length=255)),
                ('partner', models.CharField(help_text='The partner is allowed to manage support tickets            on behalf of this company.', max_length=255)),
            ],
        ),
    ]
