# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_delete_partnership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='invited_by',
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
