# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='idp_uuid',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
    ]
