# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_userprofile_idp_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sticky',
        ),
    ]
