# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20160808_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='partnership',
            unique_together=set([]),
        ),
    ]
