# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20160809_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='profiles.Company'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='profiles.Company'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_association',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='named_users', to='profiles.Company'),
        ),
    ]
