# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[(b'SUP', b'Support'), (b'REV', b'Review')], default='SUP', max_length=30),
            preserve_default=False,
        ),
    ]
