# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_userprofile_receive_all_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='receive_all_notifications',
            field=models.BooleanField(default=False, help_text=b'Subscribe to notifications for tickets created by your colleagues'),
        ),
    ]
