# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-23 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20161012_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='crm_uuid',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
    ]
