# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-21 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_userprofile_crm_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name='username'),
        ),
    ]
