# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-25 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_auto_20170801_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='entitlements',
            field=models.CharField(blank=True, max_length=500, verbose_name='entitlements'),
        ),
    ]
