# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-29 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_company_entitlements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100, verbose_name='plan')),
                ('named_contacts', models.IntegerField(default=0, verbose_name='named_contacts')),
                ('support_hours', models.IntegerField(default=0, verbose_name='support_hours')),
                ('review_hours', models.IntegerField(default=0, verbose_name='review_hours')),
            ],
        ),
    ]
