# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-15 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_auto_20170829_0659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitlements',
            options={},
        ),
        migrations.RemoveField(
            model_name='entitlements',
            name='named_contacts',
        ),
        migrations.RemoveField(
            model_name='entitlements',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='entitlements',
            name='review_hours',
        ),
        migrations.RemoveField(
            model_name='entitlements',
            name='support_hours',
        ),
        migrations.AddField(
            model_name='entitlements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2016-08-28 07:39:32', verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entitlements',
            name='entitlements',
            field=models.CharField(blank=True, max_length=500, verbose_name='entitlements'),
        ),
        migrations.AddField(
            model_name='entitlements',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2016-08-28 07:39:32', verbose_name='updated_at'),
            preserve_default=False,
        ),
    ]
