# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-15 11:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0038_entitlements_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitlements',
            options={'ordering': ['plan'], 'verbose_name_plural': 'entitlements'},
        ),
        migrations.AlterField(
            model_name='entitlements',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='entitlements',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='updated_at'),
        ),
    ]
