# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sugarcrm', '0004_auto_20160705_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sugarcrm',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='sugarcrm',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='sugarcrm',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='SugarCRM',
        ),
    ]
