# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 14:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sugarcrm', '0005_auto_20160706_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmaccount',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 9, 14, 22, 52, 652066, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crmaccount',
            name='sugarcrm_id',
            field=models.CharField(max_length=50, verbose_name='Unique identifier in SuiteCRM'),
        ),
    ]
