# Generated by Django 2.1 on 2018-08-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('created_by', models.CharField(help_text='Answer added by user', max_length=20, verbose_name='Created by')),
                ('link_url', models.URLField(blank=True, default='', max_length=255, verbose_name='Link URL')),
                ('privacy', models.CharField(blank=True, choices=[('inherit', 'Inherit'), ('public', 'Public'), ('private', 'Private')], default='inherit', max_length=255, verbose_name='Privacy')),
                ('send_copy', models.CharField(blank=True, default='', max_length=255, verbose_name='Send copy to')),
                ('is_deleted', models.BooleanField(blank=True, default=False, help_text='The answer is deleted?', verbose_name='Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Added date', verbose_name='Added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Modified date', verbose_name='Modified')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('', 'Select an issue category'), ('installation', 'Installation'), ('outages', 'Outages'), ('single_sign_on', 'Single Sign-On'), ('authentication', 'Authentication'), ('authorization', 'Authorization'), ('access_management', 'Access Management'), ('upgrade', 'Upgrade'), ('maintenance', 'Maintenance'), ('identity_management', 'Identity Management'), ('customization', 'Customization'), ('feature_request', 'Feature Request'), ('log_out', 'Logout'), ('other', 'Other')], max_length=20, verbose_name='Category')),
                ('created_by', models.CharField(max_length=20, verbose_name='Created by')),
                ('created_for', models.CharField(blank=True, max_length=20, null=True, verbose_name='Created for')),
                ('company', models.CharField(blank=True, max_length=20, null=True, verbose_name='Company Association')),
                ('updated_by', models.CharField(blank=True, max_length=20, null=True, verbose_name='Last Updated by')),
                ('assignee', models.CharField(blank=True, max_length=20, null=True, verbose_name='Assigned to')),
                ('status', models.CharField(choices=[('', 'Select a Status'), ('new', 'New'), ('assigned', 'Assigned'), ('inprogress', 'In Progress'), ('pending', 'Pending Input'), ('closed', 'Closed')], default='new', max_length=100, verbose_name='Status')),
                ('issue_type', models.CharField(blank=True, choices=[('', 'Please specify the kind of issue you have encountered'), ('outage', 'Production Outage'), ('impaired', 'Production Impaired'), ('pre_production', 'Pre-Production Issue'), ('minor', 'Minor Issue'), ('new_development', 'New Development Issue')], default='', max_length=20, verbose_name='Issue type')),
                ('server_version', models.CharField(choices=[('', 'Select Gluu Server Version'), ('3.1.2', 'Gluu Server 3.1.2'), ('3.1.1', 'Gluu Server 3.1.1'), ('3.1.0', 'Gluu Server 3.1.0'), ('3.0.2', 'Gluu Server 3.0.2'), ('3.0.1', 'Gluu Server 3.0.1'), ('2.4.4.3', 'Gluu Server 2.4.4.3'), ('2.4.4.2', 'Gluu Server 2.4.4.2'), ('2.4.4', 'Gluu Server 2.4.4'), ('2.4.3', 'Gluu Server 2.4.3'), ('2.4.2', 'Gluu Server 2.4.2'), ('Other', 'Other')], default='', max_length=10, verbose_name='Gluu Server Version')),
                ('server_version_comments', models.CharField(blank=True, max_length=30, null=True, verbose_name='Gluu Server Version Comments')),
                ('os_version', models.CharField(blank=True, choices=[('', 'Select Operating System'), ('Ubuntu', 'Ubuntu'), ('CentOS', 'CentOS'), ('Rhel', 'RHEL'), ('Debian', 'Debian')], max_length=8, null=True, verbose_name='Which OS are you using?')),
                ('os_version_name', models.FloatField(blank=True, null=True, verbose_name='OS Version')),
                ('answers_no', models.IntegerField(blank=True, default=0, verbose_name='Answers number')),
                ('link', models.URLField(blank=True, default='', max_length=255, verbose_name='Link URL')),
                ('send_copy', models.CharField(blank=True, default='', max_length=255, verbose_name='Send copy to')),
                ('is_private', models.BooleanField(blank=True, default=False, verbose_name='Private')),
                ('is_deleted', models.BooleanField(blank=True, default=False, verbose_name='Deleted')),
                ('os_type', models.BooleanField(blank=True, default=False, verbose_name='Is it 64-bit hardware?')),
                ('ram', models.BooleanField(blank=True, default=False, verbose_name='Does the server have at least 4GB RAM?')),
                ('visits', models.IntegerField(default=0, verbose_name='Ticket visits')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta keywords')),
                ('set_default_gluu', models.BooleanField(blank=True, default=False, verbose_name='Default Gluu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='ticket',
            field=models.ForeignKey(help_text='Ticket', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_answers', to='tickets.Ticket', verbose_name='Ticket'),
        ),
    ]
