# Generated by Django 2.1 on 2018-08-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('ticket_category', models.CharField(choices=[('', 'Select an issue category'), ('installation', 'Installation'), ('outages', 'Outages'), ('single_sign_on', 'Single Sign-On'), ('authentication', 'Authentication'), ('authorization', 'Authorization'), ('access_management', 'Access Management'), ('upgrade', 'Upgrade'), ('maintenance', 'Maintenance'), ('identity_management', 'Identity Management'), ('customization', 'Customization'), ('feature_request', 'Feature Request'), ('log_out', 'Logout'), ('other', 'Other')], max_length=20, verbose_name='Category')),
                ('created_by', models.CharField(max_length=20, verbose_name='Created by')),
                ('created_for', models.CharField(blank=True, max_length=20, null=True, verbose_name='Created for')),
                ('company_association', models.CharField(blank=True, max_length=20, null=True, verbose_name='Company Association')),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True, verbose_name='Last modified by')),
                ('assigned_to', models.CharField(blank=True, max_length=20, null=True, verbose_name='Assigned to')),
                ('status', models.CharField(choices=[('', 'Select a Status'), ('new', 'New'), ('assigned', 'Assigned'), ('inprogress', 'In Progress'), ('pending', 'Pending Input'), ('closed', 'Closed')], default='new', max_length=100, verbose_name='Status')),
                ('issue_type', models.CharField(blank=True, choices=[('', 'Please specify the kind of issue you have encountered'), ('outage', 'Production Outage'), ('impaired', 'Production Impaired'), ('pre_production', 'Pre-Production Issue'), ('minor', 'Minor Issue'), ('new_development', 'New Development Issue')], default='', max_length=20, verbose_name='Issue type')),
                ('answers_no', models.IntegerField(blank=True, default=0, verbose_name='Answers number')),
                ('link_url', models.URLField(blank=True, default='', max_length=255, verbose_name='Link URL')),
                ('send_copy', models.CharField(blank=True, default='', max_length=255, verbose_name='Send copy to')),
                ('is_private', models.BooleanField(blank=True, default=False, verbose_name='Private')),
                ('is_deleted', models.BooleanField(blank=True, default=False, verbose_name='Deleted')),
                ('gluu_server_version', models.CharField(default='N/A', max_length=10, verbose_name='Gluu Server Version')),
                ('gluu_server_version_comments', models.CharField(blank=True, max_length=30, null=True, verbose_name='Gluu Server Version Comments')),
                ('os_version', models.CharField(blank=True, choices=[('', 'Select Operating System'), ('Ubuntu', 'Ubuntu'), ('CentOS', 'CentOS'), ('Rhel', 'RHEL'), ('Debian', 'Debian')], max_length=8, null=True, verbose_name='Which OS are you using?')),
                ('os_version_name', models.FloatField(blank=True, null=True, verbose_name='OS Version')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('os_type', models.BooleanField(blank=True, default=False, verbose_name='Is it 64-bit hardware?')),
                ('ram', models.BooleanField(blank=True, default=False, verbose_name='Does the server have at least 4GB RAM?')),
                ('visits', models.IntegerField(default=0, verbose_name='Ticket visits')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta keywords')),
                ('set_default_gluu', models.BooleanField(blank=True, default=False, verbose_name='Default Gluu')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-date_added'],
            },
        ),
    ]
