# Generated by Django 2.1 on 2018-08-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='company_association',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='gluu_server_version',
            new_name='server_version',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='gluu_server_version_comments',
            new_name='server_version_comments',
        ),
    ]
