# Generated by Django 2.1 on 2018-08-03 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('created_by', models.CharField(help_text='Answer added by user', max_length=20, verbose_name='Created by')),
                ('link_url', models.URLField(blank=True, default='', max_length=255, verbose_name='Link URL')),
                ('privacy', models.CharField(blank=True, choices=[('inherit', 'Inherit'), ('public', 'Public'), ('private', 'Private')], default='inherit', max_length=255, verbose_name='Privacy')),
                ('send_copy', models.CharField(blank=True, default='', max_length=255, verbose_name='Send copy to')),
                ('is_deleted', models.BooleanField(blank=True, default=False, help_text='The answer is deleted?', verbose_name='Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Added date', verbose_name='Added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Modified date', verbose_name='Modified')),
                ('ticket', models.ForeignKey(help_text='Ticket', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_answers', to='tickets.Ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
                'ordering': ['created_at'],
            },
        ),
    ]
