# Generated by Django 2.1 on 2018-08-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='upload/')),
                ('created_by', models.CharField(max_length=20)),
                ('file_src', models.TextField(blank=True, verbose_name='File Source')),
                ('is_deleted', models.BooleanField(blank=True, default=False, help_text='The document has been deleted?', verbose_name='Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tickets.Answer')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tickets.Ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
