# Generated by Django 2.1 on 2018-08-08 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotficationContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contact name', max_length=100)),
                ('number', models.CharField(help_text='Contact Number', max_length=100)),
                ('priority', models.CharField(choices=[('H', 'High'), ('L', 'Low')], default='H', help_text='Priority', max_length=1)),
                ('enabled', models.BooleanField(default=True, verbose_name='Is Enabled?')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tickets.Ticket'),
        ),
    ]
