# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0038_auto_20160307_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='inst_options',
        ),
        migrations.AddField(
            model_name='ticket',
            name='os_type',
            field=models.NullBooleanField(verbose_name='Is it 64-bit hardware?'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='os_version',
            field=models.CharField(blank=True, choices=[(b'U1404', b'Ubuntu 14.04'), (b'CentOS65', b'CentOS 6.5'), (b'CentOS66', b'CentOS 6.6'), (b'CentOS67', b'CentOS 6.7'), (b'CentOS72', b'CentOS 7.2'), (b'Rhel65', b'RHEL 6.5'), (b'Rhel66', b'RHEL 6.6'), (b'Rhel67', b'RHEL 6.7')], max_length=8, null=True, verbose_name='Which OS are you using?'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ram',
            field=models.NullBooleanField(verbose_name='Does the server have at least 4GB RAM?'),
        ),
    ]
