# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0040_auto_20160426_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='type',
            new_name='ticket_type',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(help_text='This field supports markdown language.             <a target="_blank" href="http://dillinger.io/">Information here</a>', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
