# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0043_auto_20160513_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='ticket',
            name='gluu_server_version',
            field=models.CharField(default=b'N/A', max_length=10, verbose_name='Gluu Server Version'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='gluu_server_version_comments',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Gluu Server Version Comments'),
        ),
    ]
