# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0046_auto_20160613_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='file',
            new_name='attachment',
        ),
    ]
