# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 23:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0048_auto_20160618_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_alerts',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='ticketdocuments',
            name='viewed_no',
            field=models.IntegerField(blank=True, default=0, help_text='Document number of views', verbose_name='Views'),
        ),
    ]
