# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0049_auto_20160624_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Modified'),
        ),
    ]
