# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 18:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0050_auto_20160703_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_created_for', to=settings.AUTH_USER_MODEL, verbose_name='On behalf of'),
        ),
    ]
