# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0051_ticket_created_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='ticketdocuments',
            name='crm_id',
        ),
    ]
