# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0052_auto_20160913_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_viewed',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_viewed',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='viewed_no',
        ),
        migrations.RemoveField(
            model_name='ticketdocuments',
            name='viewed_no',
        ),
        migrations.AddField(
            model_name='ticket',
            name='issue_type',
            field=models.CharField(blank=True, choices=[(b'outage', 'Production Outage'), (b'impaired', 'Production Impaired'), (b'pre_production', 'Pre-Production Issue'), (b'minor', 'Minor Issue'), (b'new_development', 'New Development Issue'), (b'community', 'Community')], default=b'', max_length=20, verbose_name='Issue type'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[(b'new', 'New'), (b'assigned', 'Assigned'), (b'inprogress', 'In Progress'), (b'pending', 'Pending Input'), (b'closed', 'Closed')], default=b'new', max_length=100, verbose_name='Status'),
        ),
    ]
