# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-03 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0055_auto_20161003_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketReminderBlacklist',
            new_name='TicketBlacklist',
        ),
    ]
