# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0056_auto_20161003_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_category',
            field=models.CharField(choices=[(b'', b'Select a Category'), (b'OUTAGE', b'Outages'), (b'IDENTITY', b'Identity Management'), (b'SSO', b'Single Sign-On'), (b'AUTH', b'Authentication'), (b'ACCESS', b'Access Management'), (b'CUSTOM', b'Customization'), (b'FEATURE', b'Feature Request'), (b'INSTALLATION', b'Installation'), (b'UPGRADE', b'Upgrade'), (b'MAINTENANCE', b'Maintenance'), (b'OTHER', b'Other')], max_length=20, null=True, verbose_name='Category'),
        ),
    ]
