# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 13:04
from __future__ import unicode_literals

from django.db import migrations
from main.utils import log_error

TICKET_CATEGORY = {
    'Customization': 'CUSTOM',
    'Feature Request': 'FEATURE',
    'Identity Management': 'IDNTY',
    'Installation': 'INSTALLATION',
    'Maintenance': 'MAINTENANCE',
    'Outages': 'OUTAGE',
    'Other': 'OTHER'
}


# def migrate_category_value(apps, schema_editor):
#
#     Ticket = apps.get_model('tickets', 'Ticket')
#
#     for ticket in Ticket.objects.all():
#
#         if ticket.integration_type:
#             ticket.ticket_category = ticket.integration_type.upper()
#         else:
#             try:
#                 ticket.ticket_category = TICKET_CATEGORY[ticket.category.name]
#             except KeyError:
#                 log_error('Invalid Ticket Category for id {}'.format(ticket.id))
#                 ticket.ticket_category = ticket.category.name
#
#         ticket.save()
#

class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0057_ticket_ticket_category'),
    ]

    # operations = [
    #     migrations.RunPython(migrate_category_value),
    # ]
