# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0058_auto_20161006_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='integration_type',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_category',
            field=models.CharField(choices=[(b'', b'Select a Category'), (b'OUTAGE', b'Outages'), (b'IDNTY', b'Identity Management'), (b'SSO', b'Single Sign-On'), (b'MFA', b'Authentication'), (b'ACCESS', b'Access Management'), (b'CUSTOM', b'Customization'), (b'FEATURE', b'Feature Request'), (b'INSTALLATION', b'Installation'), (b'UPGRADE', b'Upgrade'), (b'MAINTENANCE', b'Maintenance'), (b'OTHER', b'Other')], default='MISSING', max_length=20, verbose_name='Category'),
            preserve_default=False,
        ),
    ]
