# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0059_auto_20161006_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='slug',
        ),
    ]
