# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-22 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0062_ticket_company_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='visits',
            field=models.IntegerField(default=0, verbose_name='Ticket visits'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[(b'', b'Select a Status'), (b'new', 'New'), (b'assigned', 'Assigned'), (b'inprogress', 'In Progress'), (b'pending', 'Pending Input'), (b'closed', 'Closed')], default=b'new', max_length=100, verbose_name='Status'),
        ),
    ]
