# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-01 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0063_auto_20170322_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_sent', to='tickets.Ticket')),
            ],
        ),
    ]
