# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-01 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0064_ticketnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketnotification',
            name='is_call_sent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ticketnotification',
            name='is_txt_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketnotification',
            name='date_added',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ticketnotification',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='tickets.Ticket'),
        ),
    ]
