# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-29 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0068_ticketnotification_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketnotification',
            name='is_call_sent',
        ),
    ]
