# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-29 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0069_remove_ticketnotification_is_call_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketnotification',
            name='is_call_sent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
