# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-16 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0071_ticketnotification_is_try'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='product',
            field=models.CharField(default=b'N/A', max_length=10, verbose_name='Product'),
        ),
    ]
