# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-21 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0072_ticket_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='product_version',
            field=models.CharField(default=b'N/A', max_length=10, verbose_name='Product Version'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='os_version',
            field=models.CharField(blank=True, choices=[(b'', b'Select Operating System'), (b'Ubuntu', b'Ubuntu'), (b'CentOS', b'CentOS'), (b'Rhel', b'Rhel'), (b'Debian', b'Debian')], max_length=8, null=True, verbose_name='Which OS are you using?'),
        ),
    ]
