# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-21 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0073_auto_20170621_0519'),
    ]

    operations = [

    ]
