# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-11 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0082_auto_20170711_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='gluu_server_version',
            field=models.CharField(default=b'N/A', max_length=10, verbose_name='Gluu Server Version'),
        ),
    ]
