# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-05 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0084_auto_20170711_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='os',
            field=models.CharField(blank=True, choices=[(b'', b'Select Operating System'), (b'Ubuntu', b'Ubuntu'), (b'CentOS', b'CentOS'), (b'Rhel', b'RHEL'), (b'Debian', b'Debian')], max_length=8, null=True, verbose_name='Which OS are you using?'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue_type',
            field=models.CharField(blank=True, choices=[(b'', 'Please specify the kind of issue you have encountered'), (b'outage', 'Production Outage'), (b'impaired', 'Production Impaired'), (b'pre_production', 'Pre-Production Issue'), (b'minor', 'Minor Issue'), (b'new_development', 'New Development Issue'), (b'log_out', 'Log Out')], default=b'', max_length=20, verbose_name='Issue type'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='os_version',
            field=models.FloatField(blank=True, null=True, verbose_name='OS Version'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='os_version_comments',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='OS Version Comments'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_category',
            field=models.CharField(choices=[(b'', b'Select an issue category'), (b'installation', b'Installation'), (b'outages', b'Outages'), (b'single_sign_on', b'Single Sign-On'), (b'authentication', b'Authentication'), (b'authorization', b'Authorization'), (b'access_management', b'Access Management'), (b'upgrade', b'Upgrade'), (b'maintenance', b'Maintenance'), (b'identity_management', b'Identity Management'), (b'customization', b'Customization'), (b'feature_request', b'Feature Request'), (b'log_out', b'Logout'), (b'other', b'Other')], max_length=20, verbose_name='Category'),
        ),
    ]
