# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-11 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0086_auto_20170905_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='message_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='Message Id'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue_type',
            field=models.CharField(blank=True, choices=[(b'', 'Please specify the kind of issue you have encountered'), (b'outage', 'Production Outage'), (b'impaired', 'Production Impaired'), (b'pre_production', 'Pre-Production Issue'), (b'minor', 'Minor Issue'), (b'new_development', 'New Development Issue')], default=b'', max_length=20, verbose_name='Issue type'),
        ),
    ]
