# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-12 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0087_auto_20170911_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='message_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='message_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='Message Id'),
        ),
    ]
