# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-09 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0088_auto_20170912_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta keywords'),
        ),
    ]
