# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-25 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0089_ticket_meta_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='product',
            field=models.CharField(blank=True, choices=[(b'', b'Select a Product'), (b'GLUU', b'Gluu Server'), (b'OXD', b'OXD'), (b'SUP_GLUU', b'Super Gluu'), (b'CLUSTER', b'Cluster Manager')], default=b'', max_length=20, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='product_os_version',
            field=models.CharField(blank=True, choices=[(b'', b'Select Operating System'), (b'Ubuntu', b'Ubuntu'), (b'CentOS', b'CentOS'), (b'RHEL', b'RHEL'), (b'Debian', b'Debian'), (b'Android', b'Android'), (b'iOS', b'iOS'), (b'Both', b'Both')], default=b'', max_length=20, verbose_name='Product OS Version'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='product_os_version_name',
            field=models.FloatField(blank=True, null=True, verbose_name='Product OS Version'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='product_version',
            field=models.CharField(blank=True, choices=[(b'', b'Select Product Version'), (b'3.1.1', b'3.1.1'), (b'3.0.2', b'3.0.2'), (b'3.0.1', b'3.0.1'), (b'2.4.4.3', b'2.4.4.3'), (b'2.4.4.2', b'2.4.4.2'), (b'2.4.4', b'2.4.4'), (b'2.4.3', b'2.4.3'), (b'2.4.2', b'2.4.2'), (b'1.0', b'1.0'), (b'Alpha', b'Alpha'), (b'Other', b'Other')], default=b'', max_length=20, verbose_name='Product Version'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='os_version_comments',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='OS Version'),
        ),
    ]
