# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-26 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0090_auto_20171025_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, choices=[(b'', b'Select a Product'), (b'GLUU', b'Gluu Server'), (b'OXD', b'OXD'), (b'SUP_GLUU', b'Super Gluu'), (b'CLUSTER', b'Cluster Manager')], default=b'', max_length=20, verbose_name='Product')),
                ('product_version', models.CharField(blank=True, choices=[(b'', b'Select Product Version'), (b'3.1.1', b'3.1.1'), (b'3.0.2', b'3.0.2'), (b'3.0.1', b'3.0.1'), (b'2.4.4.3', b'2.4.4.3'), (b'2.4.4.2', b'2.4.4.2'), (b'2.4.4', b'2.4.4'), (b'2.4.3', b'2.4.3'), (b'2.4.2', b'2.4.2'), (b'1.0', b'1.0'), (b'Alpha', b'Alpha'), (b'Other', b'Other')], default=b'', max_length=20, verbose_name='Product Version')),
                ('product_os_version', models.CharField(blank=True, choices=[(b'', b'Select Operating System'), (b'Ubuntu', b'Ubuntu'), (b'CentOS', b'CentOS'), (b'RHEL', b'RHEL'), (b'Debian', b'Debian'), (b'Android', b'Android'), (b'iOS', b'iOS'), (b'Both', b'Both')], default=b'', max_length=20, verbose_name='Product OS Version')),
                ('product_os_version_name', models.FloatField(blank=True, null=True, verbose_name='Product OS Version')),
                ('date_added', models.DateTimeField(auto_now_add=True, help_text='Added date', verbose_name='Added')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Modified date', verbose_name='Modified')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='product_os_version',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='product_os_version_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='product_version',
        ),
        migrations.AddField(
            model_name='ticketproduct',
            name='ticket',
            field=models.ForeignKey(help_text='Ticket', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_product', to='tickets.Ticket', verbose_name='Ticket'),
        ),
    ]
