# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-27 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0093_auto_20171027_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='os_version_comments',
        ),
    ]
