# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-07 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0094_remove_ticket_os_version_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='gluu_server_version_comments',
        ),
        migrations.AddField(
            model_name='ticket',
            name='gluu_server_version',
            field=models.CharField(default=b'N/A', max_length=10, verbose_name='Gluu Server Version'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='os_version',
            field=models.CharField(blank=True, choices=[(b'', b'Select Operating System'), (b'Ubuntu', b'Ubuntu'), (b'CentOS', b'CentOS'), (b'Rhel', b'RHEL'), (b'Debian', b'Debian')], max_length=8, null=True, verbose_name='Which OS are you using?'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='os_version_name',
            field=models.FloatField(blank=True, null=True, verbose_name='OS Version'),
        ),
    ]
