# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-07 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0097_gluuticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='message_id',
        ),
    ]
