# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-08 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0099_auto_20171107_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='set_default_gluu',
            field=models.BooleanField(default=False, verbose_name='Set Default Gluu'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='set_default_product',
            field=models.BooleanField(default=False, verbose_name='Set Default Product'),
        ),
    ]
