# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-22 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0102_auto_20171120_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdocuments',
            name='file',
            field=models.FileField(blank=True, max_length=255, upload_to=b''),
        ),
    ]
