# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-23 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0104_auto_20171122_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdocuments',
            name='_data',
            field=models.TextField(blank=True, db_column=b'data'),
        ),
    ]
