# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-23 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0105_ticketdocuments__data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdocuments',
            name='_data',
        ),
    ]
