# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-23 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0106_remove_ticketdocuments__data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdocuments',
            name='file_size',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
