# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-04 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0108_ticketdocuments_file_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdocuments',
            name='file_size',
        ),
    ]
