# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-08 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0109_remove_ticketdocuments_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='gluuticket',
            name='set_default_gluu',
            field=models.BooleanField(default=False, verbose_name='Default Gluu'),
        ),
        migrations.AlterField(
            model_name='ticketproduct',
            name='product',
            field=models.CharField(blank=True, choices=[(b'', b'Select a Product'), (b'OXD', b'OXD'), (b'SUP_GLUU', b'Super Gluu'), (b'CLUSTER', b'Cluster Manager')], default=b'', max_length=20, verbose_name='Product'),
        ),
    ]
