# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-08 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0112_remove_ticket_set_default_gluu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='set_default_gluu',
            field=models.BooleanField(default=False, verbose_name='Default Gluu'),
        ),
    ]
