# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-11 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0114_auto_20171211_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketproduct',
            name='ios_version_name',
            field=models.FloatField(blank=True, null=True, verbose_name='iOS Version'),
        ),
        migrations.AlterField(
            model_name='ticketproduct',
            name='product_os_version_name',
            field=models.FloatField(blank=True, null=True, verbose_name='Product OS Version'),
        ),
    ]
