# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-12 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0117_auto_20180112_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='gluu_server_version_comments',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Gluu Server Version Comments'),
        ),
    ]
