export const SET_TICKET = 'setTicket'
export const SET_ANSWERS = 'setAnswers'
export const SET_COMPANIES = 'setCompanies'
export const SET_USERS = 'setUsers'
export const SET_CONSTANT = 'setConstant'
export const FETCH_TICKETS_START = 'fetchStart'
export const FETCH_TICKETS_END = 'fetchEnd'
